Implement component e-shop page
st-minhho/FE-React_Ho-Le-Nhat-Minh_STI0061 pull request #1
Opened 2022-06-30 10:22 UTC by st-minhho

#### References
- [Design](https://www.figma.com/file/CUQiZbPKOlfjHZn9hBqrPh/Fashion?node-id=8%3A194)
#### Description
- Implement component for e-shop page
#### Screenshots

#### Checklist
- [ ] Code đã được build và test ở môi trường local.
- [ ] Tất cả những lỗi cơ bản đã được tìm thấy và sửa chữa

2022-06-30 15:47 UTC, st-quangnguyen2 requested changes
@st-minhho check cmt

2022-06-30 15:47 UTC, st-quangnguyen2 commented on e-shop-app/src/app/assets/icons/index.tsx
> +}
em check hết lại các file để add new line EOF

2022-06-30 15:47 UTC, st-quangnguyen2 commented on e-shop-app/src/app/pages/home/Home.tsx
> +const Home = () => {
`file` này em đổi tên thành `index.tsx`. trong `folder``home` em thêm một `folder` tên là `components` để chứa các `section`. Mỗi `section` một `folder` trong có có `index.tsx` và các `file` `component` riêng của `section`

2022-06-30 15:47 UTC, st-quangnguyen2 commented on e-shop-app/src/app/pages/home/Home.tsx
> +          </li>
đây là 1 component

2022-06-30 15:47 UTC, st-quangnguyen2 commented on e-shop-app/src/app/pages/home/Home.tsx
> +        <ul className="banner-policy">
render ra list ko code cứng

2022-06-30 15:47 UTC, st-quangnguyen2 commented on e-shop-app/src/app/pages/home/Product.tsx
> +const Product = (props: any) => {
em để ý sẽ có 2 `section` dùng tk này vì vậy `move` qua `shared` với `ProductList`

2022-06-30 15:47 UTC, st-quangnguyen2 commented on e-shop-app/src/app/pages/home/Policy.tsx
> +const Policy = () => {
chỉ chứa 1 cái `li` thôi, còn việc render list là ở `component` khác

2022-06-30 15:47 UTC, st-quangnguyen2 commented on e-shop-app/src/app/shared/components/layout/Footer.tsx
> +                <svg width={138} height={35} viewBox="0 0 138 35" fill="none" xmlns="http://www.w3.org/2000/svg">
không để thẳng `svg` ở đây

2022-06-30 15:47 UTC, st-quangnguyen2 commented on e-shop-app/src/app/shared/components/layout/Footer.tsx
> +              </li>
viết function render list này

2022-06-30 15:47 UTC, st-quangnguyen2 commented on e-shop-app/src/app/shared/components/layout/Footer.tsx
> +                </li>
viết function render list này

2022-06-30 15:47 UTC, st-quangnguyen2 commented on e-shop-app/src/app/shared/components/layout/Footer.tsx
> +                </li>
viết function render list này

2022-06-30 15:47 UTC, st-quangnguyen2 commented on e-shop-app/src/app/shared/components/layout/Header.tsx
> +              <ul className="menu sub-menu-list">
viết function render nội dung trong này

2022-06-30 15:47 UTC, st-quangnguyen2 commented on e-shop-app/src/app/shared/components/layout/Header.tsx
> +                  <svg width={139} height={35} viewBox="0 0 139 35" fill="none" xmlns="http://www.w3.org/2000/svg">
ko dùng thẳng `svg`

2022-06-30 17:21 UTC, st-duynguyen commented on e-shop-app/src/app/assets/images/index.tsx
> +export default Images;
Check lại tất cả các file, chú ý add line trống ở cuối

2022-06-30 17:23 UTC, st-duynguyen commented on e-shop-app/src/app/pages/home/Banner.tsx
> +import Images from '../../assets/images';
tất cả những component nhỏ trong thằng Home e nên bỏ trong folder components. Vd: app/pages/home/components/Banner.tsx

2022-06-30 17:25 UTC, st-duynguyen commented on e-shop-app/src/app/pages/home/BlogList.tsx
> +import Blog from "./Blog";
K ai chia quá chi tiết như ri hết á e, thường thì chỉ cần 1 component Blogs trong đó mình truyền data zô lun, rồi map li để render ra list như cách a chỉ render Product khi chiều á

2022-06-30 17:26 UTC, st-duynguyen commented on e-shop-app/src/app/pages/home/Form.tsx
> +const Form = () => {
Tương tự nên bỏ vào components của home. Nếu cảm thấy chức năng này dùng ở nhiều trang thì nên tạo trong app/shared/partial

2022-06-30 17:27 UTC, st-duynguyen commented on e-shop-app/src/app/shared/constants/productData.tsx
> +import Images from '../../assets/images'
sửa tên file lại thành ProductData giúp a

2022-07-01 06:53 UTC, st-duynguyen approved these changes
@st-minhho will continue fix review in next PR

2022-07-01 06:53 UTC, merged