Apply Redux for e-shop pages
st-minhho/FE-React_Ho-Le-Nhat-Minh_STI0061 pull request #5
Opened 2022-07-05 10:14 UTC by st-minhho

### Description
-Apply Redux for E-shop

### Screenshot
![Uploading screencapture-localhost-3001-2022-07-05-17_13_04.png…]()

2022-07-05 16:32 UTC, st-duynguyen commented on e-shop-app/src/app/pages/cart/cart.action.ts
> +import * as TYPES from '../../shared/types'
chỗ này nên đặt tên file là cart.actions.ts nha e

2022-07-05 16:33 UTC, st-duynguyen commented on e-shop-app/src/app/pages/cart/cart.action.ts
> +}
thêm line trống cho dòng cuối cùng

2022-07-05 16:33 UTC, st-duynguyen commented on e-shop-app/src/app/pages/cart/cart.reducer.ts
> +import * as TYPES from '../../shared/types'
mấy reducer với action nên đặt thêm s nha e, ở đata là cart.reducers.ts

2022-07-05 16:34 UTC, st-duynguyen commented on e-shop-app/src/app/pages/cart/cart.reducer.ts
> +      if(newCart){
hạn chế handle logic trong thằng reducers

2022-07-05 16:35 UTC, st-duynguyen commented on e-shop-app/src/app/pages/cart/cart.action.ts
> +export const increaseToCart = (id: any) => {
Nên gọp lại 1 hàm dispatch rồi thêm params để phân biệt tăng hay giảm quantity cho gọn

2022-07-05 16:36 UTC, st-duynguyen commented on e-shop-app/src/app/pages/cart/components/CartList.tsx
> +  const renderData = (data:any) => {
thêm thằng này để làm gì vậy e?

2022-07-05 16:38 UTC, st-duynguyen commented on e-shop-app/src/app/pages/cart/cart.action.ts
> +export const addToCart = (cart: any) =>{
Thường khi gọi api sẽ có 3 actions chính đó là khi gọi api, khi api thành công, và khi api success.

2022-07-06 12:40 UTC, st-quangnguyen2 commented on e-shop-app/src/app/pages/home/components/home.actions.ts
> +    const res = await axios.get('https://6088e20da6f4a300174271e7.mockapi.io/products')
`https://6088e20da6f4a300174271e7.mockapi.io/products` thì 
`https://6088e20da6f4a300174271e7.mockapi.io/` là `apiBaseUrl`
`products` là `endpoint` 
em tạo 2 file trong thư mục config để lưu mấy cái này

2022-07-06 12:42 UTC, st-quangnguyen2 commented on e-shop-app/src/app/pages/cart/cart.reducers.ts
> +  carts: getStorage('cart', [])
tạo `StorageKeys` để lưu `'cart'`

2022-07-06 12:43 UTC, st-quangnguyen2 requested changes
@st-minhho check cmt

2022-07-07 06:58 UTC, st-duynguyen approved these changes
LGTM

2022-07-07 06:59 UTC, merged